name: Release and upload gem as asset

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build gem
        run: gem build playground.gemspec --output playground-${{ steps.get_version.outputs.VERSION }}.gem

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          body: |
            ## Installation:

            Download the gem, then `gem install` the file:
            ```
            curl -fsSL https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.VERSION }}/playground-${{ steps.get_version.outputs.VERSION }}.gem -o playground-v${{ steps.get_version.outputs.VERSION }}.gem
            gem install ./playground-${{ steps.get_version.outputs.VERSION }}.gem
            ```

            ## What's Changed
            - See commit history for detailed changes
      - name: Upload gem
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./playground-${{ steps.get_version.outputs.VERSION }}.gem
          asset_name: playground-${{ steps.get_version.outputs.VERSION }}.gem
          asset_content_type: application/octet-stream

